### ISSUE TITLE
Support of conv3D

### ISSUE THREAD

**Issue by Fair95** [sebgao/LIP#11]
Hi,

Firstly, thank you for the brillant work. It is amazing that such a seemingly "simple" idea can boost the performance so much.
I was considering using LIP in my own project. And I just wanna know if LIP is also applicable for Conv3D, i.e., if I replace all conv2d layers with conv3d with minor necessary modifications, does it still work as it was in con2d version?

Best,
Fair

**Comment by sebgao** [comment]
Hi, Fair95.

It's a good question that I haven't delved into it deep though. In my opinion, LIP as a part of 2D feature extractor, which also pools features only spatially, could still work in 3D networks. But if LIP does pooling in the extra dimension which is not a trivial extension to spatial dimensions, like temporal dim, it's hard to say whether LIP can still help perserve features when the information in the extra dimension is lost in pooling (e.g., the temporal information may be of greater importance than spatial one).

**Comment by Fair95** [comment]
@sebgao 
Thanks for the clarification. In my case, there is only an extra spatial dimention, so I guess it should be fine based on your comment, I will give it a try and hopefully there would be improvement. 
Best, 
Fair
