### ISSUE TITLE
LIP model for resnet34 

### ISSUE THREAD

**Issue by julycetc** [sebgao/LIP#2]
there is only LIP model for resnet50,do you have lip_resnet34?thanks very much!

**Comment by sebgao** [comment]
In the paper we only consider ResNets with `Bottleneck` building blocks, i.e., ResNet-50 and ResNet-101. So we don't have the LIP variant for `BasicBlock` in ResNet-18 or -34 and their corresponding pretrained models.
But you can still give it a try to modify `BasicBlock` to LIP variants like we did for `Bottleneck` and design your owned logit modules, or adopt those in the paper. We believe LIP also works for ResNet-18 and -34.

**Comment by julycetc** [comment]
Thanks very much!I will have a try.




------------------ 原始邮件 ------------------
发件人: "Ziteng Gao"<notifications@github.com>; 
发送时间: 2019年8月30日(星期五) 中午1:47
收件人: "sebgao/LIP"<LIP@noreply.github.com>; 
抄送: "风"<1506567562@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sebgao/LIP] LIP model for resnet34  (#2)




In the paper we only consider ResNets with Bottleneck building blocks, i.e., ResNet-50 and ResNet-101. So we don't have the LIP variant for BasicBlock in ResNet-18 or -34 and their corresponding pretrained models.
 But you can still give it a try to modify BasicBlock to LIP variants like we did for Bottleneck and design your owned logit modules, or adopt those in the paper. We believe LIP also works for ResNet-18 and -34.
