### ISSUE TITLE
How to decide the value of ampliﬁcation coefﬁcient

### ISSUE THREAD

**Issue by mzy97** [sebgao/LIP#5]
In paper and code implementation, you set the sigmoid function in Logit model need to amplified by 12, how to decide this value? If I change the task to image segmentation, will this value be changed, how to set it?

thanks

**Comment by sebgao** [comment]
Any large (but not too large) should be OK. But honestly, I tend to remove SoftGate (sigmoid + amplified coefficient) if the model does not meet NaN errors.

________________________________
发件人: mzy97 <notifications@github.com>
发送时间: Thursday, September 26, 2019 10:09:13 AM
收件人: sebgao/LIP <LIP@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [sebgao/LIP] How to decide the value of ampliﬁcation coefﬁcient (#5)


In paper and code implementation, you set the sigmoid function in Logit model need to amplified by 12, how to decide this value? If I change the task to image segmentation, will this value be changed, how to set it?

thanks

**Comment by mzy97** [comment]
got it, thank you
