### ISSUE TITLE
Keras Implementation 

### ISSUE THREAD

**Issue by aminullah6264** [sebgao/LIP#7]
Hi
Is there any Keras implementation of this downsampling technique?

**Comment by sebgao** [comment]
Sorry, I'm not so familiar with Keras. I'm not quite sure whether the code written below can work. But the code intuitively shows our method LIP.
```
def lip2d(x, logit, **pool_kwargs):
    aggregate = keras.layers.AveragePooling2D(**pool_kwargs)
    weight = keras.backend.exp(logit)
    return aggregate(x*weight)/aggregate(weight)
```

**Comment by aminullah6264** [comment]
Thank you for your response.
Dear can you please explain what is x and logit. How can I initialize them?

**Comment by sebgao** [comment]
`x` is the feature map to downsample and `logit` is the output of the logit module (a sub-network) and `logit` is of the same size of `x`. For more details about the initialization of the sub-network, please refer to our paper.
